/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VoiceRouteImport } from './routes/voice'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChatThreadIdRouteImport } from './routes/chat.$threadId'
import { Route as ApiVoiceTtsRouteImport } from './routes/api/voice-tts'
import { Route as ApiExploreRouteImport } from './routes/api/explore'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const VoiceRoute = VoiceRouteImport.update({
  id: '/voice',
  path: '/voice',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatThreadIdRoute = ChatThreadIdRouteImport.update({
  id: '/chat/$threadId',
  path: '/chat/$threadId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVoiceTtsRoute = ApiVoiceTtsRouteImport.update({
  id: '/api/voice-tts',
  path: '/api/voice-tts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExploreRoute = ApiExploreRouteImport.update({
  id: '/api/explore',
  path: '/api/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/voice': typeof VoiceRoute
  '/api/chat': typeof ApiChatRoute
  '/api/explore': typeof ApiExploreRoute
  '/api/voice-tts': typeof ApiVoiceTtsRoute
  '/chat/$threadId': typeof ChatThreadIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/voice': typeof VoiceRoute
  '/api/chat': typeof ApiChatRoute
  '/api/explore': typeof ApiExploreRoute
  '/api/voice-tts': typeof ApiVoiceTtsRoute
  '/chat/$threadId': typeof ChatThreadIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/voice': typeof VoiceRoute
  '/api/chat': typeof ApiChatRoute
  '/api/explore': typeof ApiExploreRoute
  '/api/voice-tts': typeof ApiVoiceTtsRoute
  '/chat/$threadId': typeof ChatThreadIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/voice'
    | '/api/chat'
    | '/api/explore'
    | '/api/voice-tts'
    | '/chat/$threadId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/voice'
    | '/api/chat'
    | '/api/explore'
    | '/api/voice-tts'
    | '/chat/$threadId'
  id:
    | '__root__'
    | '/'
    | '/voice'
    | '/api/chat'
    | '/api/explore'
    | '/api/voice-tts'
    | '/chat/$threadId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  VoiceRoute: typeof VoiceRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiExploreRoute: typeof ApiExploreRoute
  ApiVoiceTtsRoute: typeof ApiVoiceTtsRoute
  ChatThreadIdRoute: typeof ChatThreadIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/voice': {
      id: '/voice'
      path: '/voice'
      fullPath: '/voice'
      preLoaderRoute: typeof VoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$threadId': {
      id: '/chat/$threadId'
      path: '/chat/$threadId'
      fullPath: '/chat/$threadId'
      preLoaderRoute: typeof ChatThreadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/voice-tts': {
      id: '/api/voice-tts'
      path: '/api/voice-tts'
      fullPath: '/api/voice-tts'
      preLoaderRoute: typeof ApiVoiceTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/explore': {
      id: '/api/explore'
      path: '/api/explore'
      fullPath: '/api/explore'
      preLoaderRoute: typeof ApiExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  VoiceRoute: VoiceRoute,
  ApiChatRoute: ApiChatRoute,
  ApiExploreRoute: ApiExploreRoute,
  ApiVoiceTtsRoute: ApiVoiceTtsRoute,
  ChatThreadIdRoute: ChatThreadIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
